In [95]:
import tensorflow as tf
from tensorflow.keras.models import load_model
from sklearn.preprocessing import StandardScaler

import pickle
import pandas as pd
import numpy as np

In [ ]:
# load the ann train model , scaler pickel file, one hot encodeing

model = load_model('model.h5')

# load the encoader and scaler

with open('label_encoder_geo.pkl', 'rb') as file:
    label_enoder_geo = pickle.load(file)

with open('label_encoder_gender.pkl', 'rb') as file:
    label_enoder_gender = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    label_enoder_scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [97]:
import os
os.getcwd()
os.listdir()

['model.h5',
 'label _encoder_gender.pkl',
 'label _encoder_geo.pkl',
 'requirements.txt',
 'Churn_Modelling.csv',
 'prediction.ipynb',
 'scaler.pkl',
 'Ann_clacification.ipynb',
 'venv',
 'logs']

In [98]:
input_data = {
    'CreditScore' : 600,
    'Geography' : 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure' : 3,
    'Balance' : 6000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 5000
}

In [99]:
geo_encoded = label_enoder_geo.transform(
    [[input_data['Geography']]]
).toarray()

geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=label_enoder_geo.get_feature_names_out(['Geography'])
)
geo_encoded_df

/home/tessolve/Datascience/Machine Learning/NLP/ANN Clacification/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [100]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,6000,2,1,1,5000

In [101]:
input_df['Gender']=label_enoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,6000,2,1,1,5000

In [102]:
input_df = pd.concat([input_df.drop("Geography" , axis= 1), geo_encoded_df], axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,6000,2,1,1,5000,1.0,0.0,0.0

In [103]:
# scaling the input data
input_scaled = label_enoder_scaler.transform(input_df)
input_scaled

array([[-0.47154541,  0.90911166,  0.09477172, -0.69844549, -1.15940786,
         0.80510537,  0.63367318,  0.95214374, -1.63125121,  0.98019606,
        -0.57581067, -0.56349184]])

In [105]:
## prediction churn
prediction =model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

array([[0.04170809]], dtype=float32)

In [108]:
prediction_proba = prediction[0][0]
prediction_proba

np.float32(0.04170809)

In [109]:
if prediction_proba > 0.5:
    print('The customer is likely to churn')
else :
    print('The customer is not likely to churn')

The customer is not likely to churn